const actionTypes = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",

  GET_VIDEOS_SUCCESS: "GET_VIDEOS_SUCCESS",
  GET_VIDEOS_FAIL: "GET_VIDEOS_FAIL",

  GET_DETAIL_VIDEO_SUCCESS: "GET_DETAIL_VIDEO_SUCCESS",
  GET_DETAIL_VIDEO_FAIL: "GET_DETAIL_VIDEO_FAIL",
  GET_COMMENT_SUCCESS: "GET_COMMENT_SUCCESS",
  GET_COMMENT_FAIL: "GET_COMMENT_FAIL",

  GET_DETAIL_CHANNEL_SUCCESS: "GET_DETAIL_CHANNEL_SUCCESS",
  GET_DETAIL_CHANNEL_FAIL: "GET_DETAIL_CHANNEL_FAIL",

  SUB_CHANNEL: "SUB_CHANNEL",
};

export default actionTypes;
