const actionTypes = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGOUT: "LOGOUT",
  TOGGLE_MENU: "TOGGLE_MENU",
  SHOW_MENU: "SHOW_MENU",
  SET_CUR_INDEX: "SET_CUR_INDEX",

  GET_VIDEOS_SUCCESS: "GET_VIDEOS_SUCCESS",
  GET_VIDEOS_FAIL: "GET_VIDEOS_FAIL",
  GET_VIDEOS_WITH_TOKEN_SUCCESS: "GET_VIDEOS_WITH_TOKEN_SUCCESS",
  GET_VIDEOS_WITH_TOKEN_FAIL: "GET_VIDEOS_WITH_TOKEN_FAIL",

  GET_DETAIL_VIDEO_SUCCESS: "GET_DETAIL_VIDEO_SUCCESS",
  GET_DETAIL_VIDEO_FAIL: "GET_DETAIL_VIDEO_FAIL",
  GET_COMMENT_SUCCESS: "GET_COMMENT_SUCCESS",
  GET_COMMENT_FAIL: "GET_COMMENT_FAIL",
  GET_RELATED_VIDEO_SUCCESS: "GET_RELATED_VIDEO_SUCCESS",
  GET_RELATED_VIDEO_FAIL: "GET_RELATED_VIDEO_FAIL",

  GET_DETAIL_CHANNEL_SUCCESS: "GET_DETAIL_CHANNEL_SUCCESS",
  GET_DETAIL_CHANNEL_FAIL: "GET_DETAIL_CHANNEL_FAIL",

  SEARCH_VIDEO_SUCCESS: "SEARCH_VIDEO_SUCCESS",
  SEARCH_VIDEO_FAIL: "SEARCH_VIDEO_FAIL",

  CHECK_SUBS_SUCCESS: "CHECK_SUBS_SUCCESS",
  CHECK_SUBS_FAIL: "CHECK_SUBS_FAIL",
  SUB_CHANNEL: "SUB_CHANNEL",
};

export default actionTypes;
